export enum Colors {
    GRAY =  "gray",
    BLUE = "blue",
    RED = "red",
    BLACK = "black",
    GREEN = "green",
    YELLOW = "yellow",
    ORANGE = "orange",
    PURPLE = "purple",
    PINK = "pink",
    CYAN = "cyan",
    MAGENTA = "magenta",
    TEAL = "teal",
    LIME = "lime",
    ZINC = "zinc",
    NEUTRAL = "neutral",
    STONE = "stone",
    SLATE = "slate",
    COOL_GRAY = "coolGray",
    WARM_GRAY = "warmGray",
    INDIGO = "indigo",
    VIOLET = "violet",
    AMBER = "amber",
}